name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPROXY: "https://proxy.golang.org,direct"
      ENABLE_DOCKER_INTEGRATION_TESTS: TRUE

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
        id: go

      - name: install staticcheck
        run: |
          cd /tmp && go install honnef.co/go/tools/cmd/staticcheck@v0.7.0

      - name: Make tests
        run: |
          make
